version: "3.8"

services:
  backend:
    build: ./backend-files
    ports:
      - "9000:9000"
    volumes:
      - ./backend-files:/app

  frontend:
    build: ./gradio-files
    ports:
      - "7861:7861"
    volumes:
      - ./gradio-files:/workspace
    depends_on:
      - backend
